Repository Yash-Ainapure/dypcetclubs.live, pull requests merged in 2024-10, with the labels that each got.

#14 title-name #11
  frontend/index.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#29 Feat: Add contributors action workflow
  .github/workflows/add-contributors.yml
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level2

#36 Issue fix #30 Redesign Club Registration form
  frontend/src/appComponents/ClubRegistration.tsx
  frontend/src/lib/utils.ts
Labels: gssoc-ext, hacktoberfest-accepted, level2

#68 Updated Logo and Title link
  frontend/src/appComponents/Navdar.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#70 Quiz Ui Redesign
  frontend/src/appComponents/QuizPage.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#86 scroll bar remove : #46 done
  frontend/src/App.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#85 favicon added
  frontend/index.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#102 solved issue of registerpage
  frontend/package-lock.json
  frontend/src/App.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#104 added favicon
  frontend/index.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#118 added functionality to add club members and display info
  backend/dist/app.js
  backend/dist/config/database.config.js
  backend/dist/controllers/club.controller.js
  backend/dist/routes/club.routes.js
  backend/package-lock.json
  backend/src/app.ts
  backend/src/config/database.config.ts
  backend/src/config/logger.ts
  backend/src/controllers/club.controller.ts
  backend/src/routes/club.routes.ts
  frontend/package-lock.json
  frontend/src/App.tsx
  frontend/src/appComponents/AddClubMembers.tsx
  frontend/src/appComponents/AdminResults.tsx
  frontend/src/appComponents/ClubAdmin.tsx
  frontend/src/appComponents/ClubCard.tsx
  frontend/src/appComponents/ClubDetails.tsx
  frontend/src/appComponents/Clubs.tsx
  frontend/src/appComponents/ClubsPage.tsx
  frontend/src/appComponents/EventCreation.tsx
  frontend/src/appComponents/Navbar.tsx
  frontend/src/appComponents/QuizCreation.tsx
  frontend/src/appComponents/axiosInstance.tsx
  frontend/src/context/AuthContext.tsx
  frontend/src/hooks/useClubs.ts
Labels: gssoc-ext, hacktoberfest-accepted, level3

#123 Enhanced UI/UX of Creation Page
  backend/package-lock.json
  backend/prisma/dev.db
  backend/prisma/dev.db-journal
  frontend/package-lock.json
  frontend/src/App.tsx
  frontend/src/appComponents/QuizCreation.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#119 Added Custom 404 Error Page
  frontend/src/App.tsx
  frontend/src/appComponents/Error.tsx
  frontend/src/assets/cat-error-page.png
Labels: gssoc-ext, hacktoberfest-accepted, level1

#141 added hiring session
  backend/prisma/dev.db
  backend/prisma/dev.db-journal
  backend/src/controllers/hiring.controller.ts
  backend/src/routes/hiring.routes.ts
  frontend/src/appComponents/AddHiringSession.tsx
  frontend/src/appComponents/ClubAdmin.tsx
  frontend/src/appComponents/HiringSessions.tsx
  frontend/src/appComponents/axiosInstance.tsx
Labels: gssoc-ext, hacktoberfest-accepted
